### ISSUE TITLE
Error after training during the sampling stage on image dataset

### ISSUE THREAD

**Issue by jbawsume** [XzwHan/CARD#17]
Hello. 
I am training the model on the dataset with 10 classes. The training successfully runs but I am finding an error after training the dataset. During the sampling stage of the process. after the mini-batch sampling takes place. I modeled the yml file similar to the cifar10. 

```shell
326it [4:08:34, 45.76s/it]INFO - card_classification.py - 2023-06-01 22:15:50,215 - Minibatch 326 sampling took 45.7197 seconds.
327it [4:09:20, 45.75s/it]
327 torch.Size([48, 10])
INFO - card_classification.py - 2023-06-01 22:15:50,323 - Begin optimizing temperature scaling parameter...
327it [00:53,  6.06it/s]
INFO - card_classification.py - 2023-06-01 22:16:44,709 - NLL of the last mini-batch: nan
INFO - card_classification.py - 2023-06-01 22:16:44,709 - Apply tuned temperature scaling parameter T with a value of nan
0it [00:01, ?it/s]
ERROR - main.py - 2023-06-01 22:16:46,813 - Traceback (most recent call last):
  File "main.py", line 297, in main
    y_majority_vote_accuracy_all_steps_list = runner.test_image_task()
  File "/root/CARD/classification/card_classification.py", line 1024, in test_image_task
    p_sample_loop_with_eval(model, x_tile, y_0_hat_tile, y_T_mean_tile, self.num_timesteps,
  File "/root/CARD/classification/card_classification.py", line 647, in p_sample_loop_with_eval
    cur_y = p_sample(model, x, y_t, y_0_hat, y_T_mean, i, alphas, one_minus_alphas_bar_sqrt)  # y_{t-1}
  File "/root/CARD/classification/diffusion_utils.py", line 78, in p_sample
    eps_theta = model(x, y, t, y_0_hat).to(device).detach()
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/CARD/classification/model.py", line 80, in forward
    x = self.encoder_x(x)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/CARD/classification/model.py", line 185, in forward
    feature = self.forward_feature(x)
  File "/root/CARD/classification/model.py", line 179, in forward_feature
    x = self.f(x)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

**Comment by jbawsume** [comment]
i was able to get rid of this error by removing normalization in the custom dataloader :

```python
if self.transform:
            #data_norm_mean, data_norm_std = (0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)
            data_norm_mean, data_norm_std = (0.5, 0.5, 0.5), (0.5, 0.5, 0.5)
            transform = torchvision.transforms.Compose([
                torchvision.transforms.ToPILImage(),
                torchvision.transforms.Resize(128),
                torchvision.transforms.ToTensor(),
                #torchvision.transforms.Normalize(mean=data_norm_mean, std=data_norm_std)
            ])
            image = transform(image)
``` 

but i am facing a different issue the code just keeps running no errors shown i had it running for more than 10 hours with no updates and it shows that it stops at the forward and i cant seem to see the cause if this. some changes i made i had reduced the sample  batch size to 12 

```shell
326it [2:07:32, 23.47s/it]INFO - card_classification.py - 2023-06-22 21:52:09,465 - Minibatch 326 sampling took 23.4514 seconds.
327it [2:07:56, 23.47s/it]
327 torch.Size([48, 10])
INFO - card_classification.py - 2023-06-22 21:52:09,648 - Begin optimizing temperature scaling parameter...
327it [00:45,  7.17it/s]
INFO - card_classification.py - 2023-06-22 21:52:55,523 - NLL of the last mini-batch: 0.33924884
INFO - card_classification.py - 2023-06-22 21:52:55,526 - Apply tuned temperature scaling parameter T with a value of 0.1921
0it [00:00, ?it/s]/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
/root/miniconda3/envs/card/lib/python3.8/site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)
84it [10:08:21, 434.54s/it]^C
Traceback (most recent call last):
  File "main.py", line 325, in <module>
    sys.exit(main())
  File "main.py", line 297, in main
    y_majority_vote_accuracy_all_steps_list = runner.test_image_task()
  File "/root/CARD/classification/card_classification.py", line 1024, in test_image_task
    p_sample_loop_with_eval(model, x_tile, y_0_hat_tile, y_T_mean_tile, self.num_timesteps,
  File "/root/CARD/classification/card_classification.py", line 647, in p_sample_loop_with_eval
    cur_y = p_sample(model, x, y_t, y_0_hat, y_T_mean, i, alphas, one_minus_alphas_bar_sqrt)  # y_{t-1}
  File "/root/CARD/classification/diffusion_utils.py", line 78, in p_sample
    eps_theta = model(x, y, t, y_0_hat).to(device).detach()
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/CARD/classification/model.py", line 80, in forward
    x = self.encoder_x(x)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/CARD/classification/model.py", line 185, in forward
    feature = self.forward_feature(x)
  File "/root/CARD/classification/model.py", line 179, in forward_feature
    x = self.f(x)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torchvision/models/resnet.py", line 74, in forward
    out = self.conv2(out)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/card/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
KeyboardInterrupt

```
